import type { AnchoredContext } from "../types.js"

// likes when user boss's him around (imperative speach)
export function formatForCursor(ctx: AnchoredContext): string {
  const lines: string[] = []

  lines.push(`# ${ctx.project.name} — Cursor Rules`)
  lines.push(`# Generated by context-anchor @ ${ctx.mergedAt}`)
  lines.push("")

  if (ctx.project.stack.length > 0) {
    lines.push("## Stack")
    ctx.project.stack.forEach((s) => lines.push(`- ${s}`))
    lines.push("")
  }

  if (ctx.project.principles.length > 0) {
    lines.push("## Rules")
    ctx.project.principles.forEach((p) => {
      // converts to imperative
      const rule = p.match(/^(always|never|use|avoid|do|don't)/i) ? p : `Always follow: ${p}`
      lines.push(`- ${rule}`)
    })
    ctx.project.conventions.forEach((c) => {
      const rule = c.match(/^(always|never|use|avoid|do|don't)/i) ? c : `Always use: ${c}`
      lines.push(`- ${rule}`)
    })
    lines.push("")
  }

  if (ctx.feature) {
    const f = ctx.feature
    lines.push(`## Active Feature: ${f.name}`)
    lines.push("")

    if (f.decisions.length > 0) {
      lines.push("### Decisions (do not change these)")
      f.decisions.forEach((d) => {
        lines.push(`- Use ${d.decision} (reason: ${d.reason})`)
        if (d.rejected) lines.push(`  - Do NOT suggest ${d.rejected} — already rejected`)
      })
      lines.push("")
    }

    if (f.constraints.length > 0) {
      lines.push("### Constraints")
      f.constraints.forEach((c) => lines.push(`- ${c}`))
      lines.push("")
    }

    const { pending } = f.state
    if (pending.length > 0) {
      lines.push("### Next tasks")
      pending.forEach((p) => lines.push(`- [ ] ${p}`))
      lines.push("")
    }
  }

  return lines.join("\n")
}